---
alertmanager_web_external_url: "http://0.0.0.0:9093/alertmanager"
alertmanager_slack_api_url: "http://example.org"
alertmanager_receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    channel: '#alerts'
alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: slack

prometheus_db_dir: /opt/data/prometheus
prometheus_storage_retention: "365d"
prometheus_web_external_url: "http://0.0.0.0:9090/prometheus"
grafana_data_dir: /opt/data/grafana
grafana_url: "http://0.0.0.0:3000/grafana/"
grafana_security:
  admin_user: admin
  admin_password: password


node_exporter_enabled_collectors: ['systemd','ntp','processes','supervisord']
