---
- name: ensure Prometheus exporters directory exist
  file:
    path: "{{ rabbitmq_exporter_install_dir }}"
    state: directory

- name: Unarchive rabbitmq Exporter
  unarchive:
    remote_src: yes
    dest: "{{ rabbitmq_exporter_install_dir }}"
    src: "{{ rabbitmq_exporter_url }}"
    creates: "{{ rabbitmq_exporter_binary }}"
  notify: restart rabbitmq exporter

- name: create systemd service unit
  template:
    src: rabbitmq-exporter.service.j2
    dest: /etc/systemd/system/rabbitmq-exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - rabbitmq exporter service reenable
    - restart rabbitmq exporter

- meta: flush_handlers

- name: ensure prometheus rabbitmq exporter service is enabled and started
  service:
    name: rabbitmq-exporter
    state: started
    enabled: yes
