---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create default site config file
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx server

