---
rabbitmq_exporter_install_dir: "/opt/prometheus-exporters/rabbitmq-exporter"
rabbitmq_exporter_version:  "1.0.0-RC6.1"
rabbitmq_exporter_release_name: "rabbitmq_exporter-{{ rabbitmq_exporter_version }}.linux-amd64"
rabbitmq_exporter_url: "https://github.com/kbudde/rabbitmq_exporter/releases/download/v{{ rabbitmq_exporter_version }}/{{ rabbitmq_exporter_release_name }}.tar.gz"
rabbitmq_exporter_binary: "{{ rabbitmq_exporter_install_dir }}/{{ rabbitmq_exporter_release_name }}/rabbitmq_exporter"
rabbit_user: 'guest'
rabbit_password: 'guest'
rabbitmq_exporter_config_flags:
  'rabbit_url': 'http://localhost:15672'
  'rabbit_user': '{{ rabbit_user }}'
  'rabbit_password': '{{ rabbit_password }}'
  'publish_port': '9419'
  'skipverify': 'false'
  'include_queues': '.*'
  'skip_queues': '^$'
  'rabbit_capabilities': 'no_sort,bert'
  'rabbit_exporter': 'exchange,node,overview,queue'
