---
nginx_exporter_install_dir: "/opt/prometheus-exporters/nginx-exporter"
nginx_exporter_version: "0.8.0"
nginx_exporter_name: "nginx-prometheus-exporter-{{ nginx_exporter_version }}-linux-amd64"
nginx_exporter_url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/{{ nginx_exporter_name }}.tar.gz"
nginx_exporter_binary: "{{ nginx_exporter_install_dir }}/nginx-prometheus-exporter"
nginx_exporter_port: 9113
nginx_exporter_listen_address: "0.0.0.0:{{ nginx_exporter_port }}"
nginx_exporter_scrape_uri: http://127.0.0.1:80/nginx_stub_status
nginx_exporter_nginx_plus: false
