{
 "title": "Airflow Dashboard",
 "description": "Dashboard to view airflow",
 "tags": [ "Airflow" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(airflow_up,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Task Runs (running/success/failed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (event) (airflow_event_total{instance=\"$node\",event=\"success\"})",
     "legendFormat": "{{ event }}"
    },
    {
     "expr": "sum by (event) (airflow_event_total{instance=\"$node\",event=\"failed\"})",
     "legendFormat": "{{ event }}"
    },
    {
     "expr": "sum by (event) (airflow_event_total{instance=\"$node\",event=\"running\"})",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "DAG Runs (running/success/failed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (airflow_dag_run_state{instance=\"$node\",state=\"running\"})",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "sum by (state) (airflow_dag_run_state{instance=\"$node\",state=\"failed\"})",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "sum by (state) (airflow_dag_run_state{instance=\"$node\",state=\"success\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Airflow Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "airflow_up" }
   ]
  },
  {
   "title": "Airflow  DAG List",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(dag) (airflow_dag_active{instance=\"$node\"})",
     "legendFormat": "{{ dag }}"
    }
   ]
  },
  {
   "title": "Airflow Exporter Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_scrape_failures_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}