{
 "title": "Celery Monitoring",
 "description": "Celery metrics monitoring from prometheus datasource",
 "tags": [ "celery" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "exporter", "query": "celery_workers" },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "TIME_FRAME", "query": "30s,1m,2m,5m,10m,15m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Celery workers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(celery_workers{job=~\"$job\"})"
    }
   ]
  },
  { "title": "Celery workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Summpary task by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(celery_tasks[$TIME_FRAME])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Task runtime summary",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(celery_tasks_runtime_seconds_sum[$TIME_FRAME])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Task latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(celery_task_latency_sum[$TIME_FRAME])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Top 15 active tasks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum(rate(celery_tasks_by_name{state='STARTED'}[$TIME_FRAME])) by (app, name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 15 reciaved tasks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum(rate(celery_tasks_by_name{state='RECEIVED'}[$TIME_FRAME])) by (app, name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 15 pending tasks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum(rate(celery_tasks_by_name{state='PENDING'}[$TIME_FRAME])) by (app, name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 15 failed tasks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum(rate(celery_tasks_by_name{state='FAILURE'}[$TIME_FRAME])) by (app, name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 15 retrying tasks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum(rate(celery_tasks_by_name{state='RETRY'}[$TIME_FRAME])) by (app, name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 15 finished tasks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum(rate(celery_tasks_by_name{state='SUCCESS'}[$TIME_FRAME])) by (app, name))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}