{
 "title": "CouchDB Dashboard",
 "description": "Please leave a review for me to add if there are anymore necessary for the dashboard to apply. ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node Name",
    "query": "label_values(couchdb_httpd_node_up,node_name)"
   },
   {
    "name": "db",
    "label": "DB",
    "query": "label_values(couchdb_database_doc_count,db_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Up",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(couchdb_httpd_node_up{node_name=~\"$node\"})",
     "legendFormat": "{{ node _name }}"
    }
   ]
  },
  {
   "title": "Open Database",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(couchdb_httpd_open_databases{node_name=~ \"$node\"})"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(couchdb_httpd_open_os_files{node_name=~ \"$node\"})"
    }
   ]
  },
  {
   "title": "Doc Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(couchdb_database_doc_count{db_name=~\"$db\"})"
    }
   ]
  },
  {
   "title": "Data size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(couchdb_database_data_size{db_name=~ \"$db\"})"
    }
   ]
  },
  {
   "title": "Disk size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(couchdb_database_disk_size{db_name=~ \"$db\"})"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(couchdb_httpd_requests{node_name=~ \"$node\"}[5m]))",
     "legendFormat": "http_requests"
    }
   ]
  },
  {
   "title": "Number of HTTPD requests by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(couchdb_httpd_request_methods{node_name=~ \"$node\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Workload - Reads (green) & Writes (yellow)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(couchdb_httpd_database_reads{node_name=~ \"$node\"}[5m]))"
    },
    {
     "expr": "sum(rate(couchdb_httpd_database_writes[5m]))"
    }
   ]
  },
  {
   "title": "Auth cache hits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(couchdb_httpd_auth_cache_hits) / (sum(couchdb_httpd_auth_cache_hits) + sum(couchdb_httpd_auth_cache_misses)) * 100",
     "legendFormat": "Cache_hits"
    }
   ]
  },
  {
   "title": "Bulk requets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(couchdb_httpd_bulk_requests{node_name=~ \"$node\"}) by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "HTTP request by Status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(couchdb_httpd_status_codes{node_name=~ \"$node\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Change Feed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(couchdb_httpd_clients_requesting_changes{node_name=~ \"$node\"})",
     "legendFormat": "{{ change feed}}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(couchdb_server_active_tasks)",
     "legendFormat": "Active tasks"
    }
   ]
  },
  {
   "title": "Doc Update",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(couchdb_fabric_doc_update{node_name=~ \"$node\"}[5m])) by(metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "View Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(couchdb_httpd_view_reads{node_name=~ \"$node\"}[5m]))",
     "legendFormat": "{{view reads}}"
    }
   ]
  },
  {
   "title": "Couchdb Replicator worker death",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(couchdb_replicator_worker_deaths{node_name=~ \"$node\"})",
     "legendFormat": "Replicator worker death"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(couchdb_httpd_request_time{node_name=~ \"$node\"}[5m])) by(instance)"
    }
   ]
  },
  {
   "title": "Compaction Running",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(couchdb_database_compact_running{db_name=~ \"$db\"})"
    }
   ]
  },
  {
   "title": "Log Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(couchdb_server_couch_log{level=\"critical\",node_name=~\"$node\"}) ",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "sum(couchdb_server_couch_log{level=\"alert\",node_name=~ \"$node\"}) ",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}