{
 "title": "HAproxy Servers",
 "description": "HAproxy backend servers",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "alias",
    "label": "Load Balancer",
    "query": "label_values(haproxy_up, alias)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_server_bytes_in_total{alias=\"$alias\"}, backend)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_bytes_in_total{alias=\"$alias\", backend=~\"$backend\"}, server)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_server_http_responses_total{alias=\"$alias\", backend=~\"$backend\", server=~\"$server\"}, code)"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(haproxy_backend_current_queue{backend=\"$backend\"})"
    }
   ]
  },
  {
   "title": "Haproxy up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    { "expr": "sum(haproxy_up)" }
   ]
  },
  {
   "title": "Backend Conn Error",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(haproxy_backend_connection_errors_total{backend=\"$backend\"})"
    }
   ]
  },
  {
   "title": "Response Time(sec)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(haproxy_backend_http_response_time_average_seconds{backend=\"$backend\"})"
    }
   ]
  },
  {
   "title": "Backend Success(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(haproxy_backend_http_responses_total{code=\"2xx\"}) / sum(haproxy_backend_http_responses_total) * 100"
    }
   ]
  },
  {
   "title": "Fronted Success(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(haproxy_frontend_http_responses_total{code=\"2xx\"}) / sum(haproxy_frontend_http_responses_total) * 100"
    }
   ]
  },
  { "title": "Backend Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{backend=~\"$backend\", server=~\"$server\", code=~\"$code\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}/{{ code }}"
    }
   ]
  },
  {
   "title": "Check Duration (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(haproxy_server_check_duration_milliseconds{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}) without (alias)",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Check Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_check_failures_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Downtime (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_downtime_seconds_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Redispatch Warnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_redispatch_warnings_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_response_errors_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Retry Warnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_retry_warnings_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_in_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_out_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "New Connections Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connections_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connection_errors_total{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Current Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_queue{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Max Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_queue{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_session_rate{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Max Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_sessions{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_session_rate{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Servers UP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_up{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Servers Weights",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_weight{backend=~\"$backend\", server=~\"$server\", alias=\"$alias\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  }
 ]
}