{
 "title": "Nginx Statistics",
 "description": "Dashboard for Nginx Statistics.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\"}[5m])*8",
     "legendFormat": "receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\"}[5m])*8",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Processed Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_handled{instance=\"$instance\"}[5m])",
     "legendFormat": "Handled"
    },
    {
     "expr": "irate(nginx_http_requests_total{instance=\"$instance\"}[5m])",
     "legendFormat": "request_total"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_current{instance=\"$instance\", state=\"active\"}",
     "legendFormat": "{{state}} (Active client connections including Waiting connections)",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "nginx_connections_reading{instance=\"$instance\"}",
     "legendFormat": "reading"
    },
    {
     "expr": "nginx_connections_writing{instance=\"$instance\"}",
     "legendFormat": "writing"
    },
    {
     "expr": "nginx_connections_waiting{instance=\"$instance\"}",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Nginx status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nginx_up{instance=\"$instance\"}"
    }
   ]
  }
 ]
}