{
 "title": "pgbouncer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(pgbouncer_up,instance)"
   },
   { "name": "top", "label": "Top", "query": "5,10,15" }
  ]
 },
 "panels": [
  {
   "title": "Server connection in Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top,max_over_time(pgbouncer_pools_server_used_connections{instance =~ \"$server\"}[${__range}]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server connection Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top, max_over_time(pgbouncer_pools_server_active_connections{instance =~ \"$server\"}[${__range}]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server connection Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top, max_over_time(pgbouncer_pools_server_idle_connections{instance =~ \"$server\"}[${__range}]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Client connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top, max_over_time(pgbouncer_pools_client_active_connections{instance =~ \"$server\"}[${__range}]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waiting Client connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top, max_over_time(pgbouncer_pools_client_waiting_connections{instance =~ \"$server\"}[${__range}]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maxwait Client conn(sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top, max_over_time(pgbouncer_pools_client_maxwait_seconds{instance =~ \"$server\"}[${__range}]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slowest query time(millisec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk($top,max_over_time(pgbouncer_stats_transactions_duration_microseconds{instance =~ \"$server\"}[${__range}]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pgbouncer Database currnet conn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($top, max_over_time(pgbouncer_databases_database_current_connections{instance =~ \"$server\"}[${__range}]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Active/used/Idle Connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_server_active_connections{instance=~ \"$server\"})",
     "legendFormat": "Total-Active"
    },
    {
     "expr": "sum(pgbouncer_pools_server_used_connections{instance=~ \"$server\"})",
     "legendFormat": "Total-Used"
    },
    {
     "expr": "sum(pgbouncer_pools_server_idle_connections{instance=~ \"$server\"})",
     "legendFormat": "Total-Idle"
    }
   ]
  },
  {
   "title": "pgbouncer Down",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pgbouncer_up{instance =~ \"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Query time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (instance) ( rate(pgbouncer_stats_queries_duration_microseconds{instance=~\"$server\"}[5m]) ) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total of incoming/outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (instance,database) ( rate(pgbouncer_stats_received_bytes_total{instance=~\"$server\"}[5m])*8 ) )",
     "legendFormat": "{{ database }}: Stats received bytes total"
    },
    {
     "expr": "sort_desc( sum by (instance,database) ( rate(pgbouncer_stats_sent_bytes_total{instance=~\"$server\"}[5m])*8 ) )",
     "legendFormat": "{{ database }}: Stats sent bytes total"
    }
   ]
  },
  {
   "title": "Database pool size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(database)(pgbouncer_databases_database_pool_size{instance=~\"$server\"})",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}