{
 "title": "RabbitMQ Monitoring",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(rabbitmq_running, instance)"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(rabbitmq_queue_state==1)" }
   ]
  },
  {
   "title": "Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(rabbitmq_queue_consumers)", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_connections{instance =~\"$node\"})"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_channels{instance =~\"$node\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages{instance =~\"$node\"})"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{instance =~\"$node\"})"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (cluster) (rate(rabbitmq_exchange_messages_published_in_total{instance =~\"$node\"}[1m]))"
    }
   ]
  },
  {
   "title": "Messages Out",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (cluster) (rate(rabbitmq_exchange_messages_published_out_total{instance =~\"$node\"}[1m]))"
    }
   ]
  },
  {
   "title": "Unacknowledge",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged{instance =~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory limit Alarm",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_alarm{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk limit Alarm",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_node_disk_free_alarm{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(rabbitmq_running{instance=~\"$node\",self=\"1\",service=\"rabbitmq\"})",
     "legendFormat": "nodes"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rabbitmq_queue_messages{instance =~ \"$node\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_ready{instance =~ \"$node\"}[1m])",
     "legendFormat": "{{queue}}:ready"
    },
    {
     "expr": "rate(rabbitmq_queue_messages_published_total{instance =~ \"$node\"}[1m])",
     "legendFormat": "{{queue}}:published"
    },
    {
     "expr": "rate(rabbitmq_queue_messages_delivered_total{instance =~ \"$node\"}[1m])",
     "legendFormat": "{{queue}}:delivered"
    },
    {
     "expr": "rate(rabbitmq_queue_messages_unacknowledged{instance =~ \"$node\"}[1m])",
     "legendFormat": "{{queue}}:unack"
    }
   ]
  },
  {
   "title": "Consumer Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumer_utilisation",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Queues by depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_published_total",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Node status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "File Descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rabbitmq_fd_used)", "legendFormat": "fd used" },
    { "expr": "sum(rabbitmq_fd_available)", "legendFormat": "fd available" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_used{instance=~\"$node\"}) by (instance) / sum(rabbitmq_node_mem_limit{instance=~\"$node\"}) by (instance) *100",
     "legendFormat": "mem used (%)"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "min(rabbitmq_node_disk_free{instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{node}}:free"
    },
    {
     "expr": "min(rabbitmq_node_disk_free_limit{instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{node}}:limit"
    }
   ]
  }
 ]
}