- name: copy custom queries file
  copy:
     src: files/queries.yml
     dest: "{{ postgres_exporter_home }}/queries.yml"
     owner: "{{ postgres_exporter_user }}"
     group: "{{ postgres_exporter_group }}"
     mode: "u=r,g=r,o="
  notify: restart postgres_exporter
