pg_replication:
  query: "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())) as delay"
  master: true
  metrics:
    - delay:
        usage: "GAUGE"
        description: "Replication delay in seconds"

pg_locks:
  query: "SELECT pgdb.datname AS database, count(*) FROM pg_locks pl, pg_database pgdb WHERE pl.database = pgdb.oid AND NOT pl.granted GROUP BY pgdb.datname"
  master: true
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - not_granted:
        usage: "GAUGE"
        description: "Locks not granted"

pg_conn:
  query: "SELECT datname, state, count(pid) FROM pg_stat_activity WHERE datname != 'postgres' GROUP BY datname, state"  
  master: true
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - state:
        usage: "LABEL"
        description: "Locks not granted"
    - count:
        usage: "GAUGE"
        description: "stats count per DB"

pg_database:
  query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database"
  master: true
  cache_seconds: 30
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - size_bytes:
        usage: "GAUGE"
        description: "Disk space used by the database"
