- name: ensure Prometheus exporter directory exist
  file:
    path: "{{ zookeeper_exporter_install_dir }}"
    state: directory

- name: unarchive zookeeper Exporter
  unarchive:
    remote_src: yes
    dest: "{{ zookeeper_exporter_install_dir }}"
    src: "{{ zookeeper_exporter_url }}"
    creates: "{{ zookeeper_exporter_binary }}"
  notify: restart zookeeper exporter

- name: create systemd script
  template:
    src: zookeeper_exporter.service.j2
    dest: /etc/systemd/system/zookeeper_exporter.service
  notify: restart zookeeper exporter

- meta: flush_handlers

- name: Make sure zookeeper exporter is started
  service:
    name: zookeeper_exporter
    state: started
    enabled: yes

