- name: Create Prometheus DB directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus
 
- name: Configure enabled Prometheus targets
  template:
    src: "targets/{{ item.name }}.json.j2"
    dest: "/etc/prometheus/file_sd/{{ item.name }}.json"
    owner: prometheus
    group: prometheus
    mode: 0660
  when: item is defined and item.enabled|default(True)
  loop: "{{ prometheus_custom_targets }}"
  notify: restart prometheus
  tags: prometheus_targets

- name: Remove disabled Prometheus targets
  file:
    path: "/etc/prometheus/file_sd/{{ item.name }}.json"
    state: absent
  when: item is not defined or not item.enabled|default(True)
  loop: "{{ prometheus_custom_targets }}"
  notify: restart prometheus
  tags: prometheus_targets

- name: Sets /etc/hosts
  become: yes
  blockinfile:
    dest: /etc/hosts
    block: |
      {% for host in groups.all|sort -%}
      {{ host }} {{ hostvars[host].alt_hostname | default(hostvars[host].hostname) }}
      {% endfor -%}
  when: prometheus_monitoring_enabled| default(False)
  tags: always
