- name: Configure  Prometheus
  template: src=prometheus.yml.j2 dest=/etc/prometheus/prometheus.yml
  tags: prometheus
  notify: restart prometheus

- name: Configure  Prometheus Node exporter target 
  template: src=node_exporter_target.json.j2 dest=/etc/prometheus/node_exporter_target.json
  tags: prometheus
  notify: restart prometheus

