- name: Create Prometheus DB directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus
 
- name: Configure Prometheus target
  template:
    src: "{{ item }}"
    dest: /etc/prometheus/file_sd/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: prometheus
    group: prometheus
    mode: 0660
  with_fileglob:
    - ../templates/targets/*.json.j2
  notify: restart prometheus
  tags: prometheus_targets

- name: Sets /etc/hosts
  become: yes
  blockinfile:
    dest: /etc/hosts
    block: |
      {% for host in groups.all|sort -%}
      {{ host }} {{ hostvars[host].alt_hostname | default(hostvars[host].hostname) }}
      {% endfor -%}
  when: prometheus_monitoring_enabled| default(False)
  tags: always
