- name: Create Prometheus DB directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus
 
- name: Configure  Prometheus
  template: 
    src: prometheus.yml.j2 
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
  tags: prometheus_config
  notify: restart prometheus

- name: Configure Prometheus target
  template:
    src: "{{ item }}"
    dest: /etc/prometheus/file_sd/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: prometheus
    group: prometheus
  with_fileglob:
    - ../templates/targets/*.json.j2
  notify: restart prometheus
  tags: prometheus_targets

- name: Remove default alert rules file
  file:
    path: /etc/prometheus/rules/ansible_managed.rules
    state: absent

- name: Copy Alert rules file
  copy:
    src: "{{ item }}"
    dest: /etc/prometheus/rules/{{item | basename }}
    owner: prometheus
    group: prometheus
  with_fileglob:
    - ../files/rules/*.rules  
  notify: restart prometheus
  tags: prometheus_alerts

- name: Sets /etc/hosts
  become: yes
  blockinfile:
    dest: /etc/hosts
    block: |
      {% for host in groups.all -%}
      {{ host }} {{ hostvars[host].alt_hostname | default(hostvars[host].hostname) }}
      {% endfor -%}
  when: prometheus_monitoring_enabled| default(False)
  tags: always
