- name: Create Prometheus DB directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus
 
- name: Configure  Prometheus
  template: src=prometheus.yml.j2 dest=/etc/prometheus/prometheus.yml
  tags: prometheus
  notify: restart prometheus

- name: Configure Prometheus target
  template:
    src: "{{ item }}"
    dest: /etc/prometheus/file_sd/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - ../templates/*_target.json.j2
  notify: restart prometheus

 - name: Copy Alert rules file
  copy:
    src: "{{ role_path }}/files/rules/rules.yml"
    dest: /etc/prometheus/rules/rules.yml
  notify: restart prometheus

- name: Sets /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regex: '^{{ item }}.*'
    line: "{{ item }} {{ hostvars[item].alt_hostname | default(hostvars[item].hostname) }}" 
  with_items: "{{ groups.all }}"
  when: prod_mode| default(False) 
